[".ansible/collections/ansible_collections/technohouser"]
  refreshPeriod = "1h"
  type = "git-repo"
  url = "https://github.com/borland502/technohouser"
[".ansible/collections/ansible_collections/proxmox-ansible"]
  refreshPeriod = "1h"
  type = "git-repo"
  url = "https://github.com/borland502/proxmox-ansible.git"
[".ansible/plugins/lookup"]
  refreshPeriod = "9600h"
  type = "file"
  url = "https://github.com/christian-heusel/ansible-lookup-plugin-gopass/blob/main/lookup_plugins/gopass.py"
[".ansible/collections/requirements.yml"]
  refreshPeriod = "2h"
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/ansible/collections/requirements.yml"
[".ansible/roles/requirements.yml"]
  refreshPeriod = "2h"
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/ansible/roles/requirements.yml"
