[".local/share/automation/dasbootstrap"]
  refreshPeriod = "72h"
  type = "git-repo"
  url = "https://github.com/borland502/dasbootstrap.git"
[".local/share/automation/install.doctor"]
  refreshPeriod = "72h"
  type = "git-repo"
  url = "https://github.com/megabyte-labs/install.doctor"
[".local/share/automation/chezmoi"]
  refreshPeriod = "168h"
  type = "git-repo"
  url = "https://github.com/borland502/dotfiles.git"
[".local/share/automation/acme.sh"]
  refreshPeriod = "72h"
  type = "git-repo"
  url = "https://github.com/borland502/acme.sh.git"
[".local/share/automation/Proxmox"]
  refreshPeriod = "72h"
  type = "git-repo"
  url = "https://github.com/borland502/Proxmox"
[".local/share/automation/home-ops"]
  refreshPeriod = "72h"
  type = "git-repo"
  url = "https://github.com/borland502/home-ops"
