[".local/share/automation/dasbootstrap"]
  type = "git-repo"
  url = "https://github.com/borland502/dasbootstrap.git"
[".local/share/automation/install.doctor"]
  type = "git-repo"
  url = "https://github.com/borland502/install.doctor.git"
[".local/share/automation/chezmoi"]
  type = "git-repo"
  url = "https://github.com/borland502/dotfiles.git"
[".ansible"]
  type = "git-repo"
  url = "https://gitea.npm.technohouser.com/jhettenh/secrets"
