[".local/share/dasbootstrap"]
  type = "git-repo"
  url = "https://github.com/borland502/dasbootstrap.git"
[".local/share/install.doctor"]
  type = "git-repo"
  url = "https://github.com/borland502/install.doctor.git"