[".local/lib/logger.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/lib/logger.sh"
[".local/lib/constants.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/lib/constants.sh"
[".local/lib/functions.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/lib/functions.sh"
[".local/lib/install_doctor_functions.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/lib/install_doctor_functions.sh"
[".local/lib/util_functions.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/borland502/dasbootstrap/main/lib/util_functions.sh"
