[tool.poetry]
name = "poetry-instance"
version = "1.8.2"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.12.3"
poetry = "1.8.2"

[tool.poetry.group.additional.dependencies]
poetry-multiproject-plugin = "^1.5.0"

