[vim]
  plugins = [
    "Plugin 'VundleVim/Vundle.vim'",
    "Plugin 'alker0/chezmoi.vim'",
    "Plugin 'google/vim-codefmt'",
    "Plugin 'google/vim-glaive'",
    "Plugin 'google/vim-maktaba'",
    "Plugin 'phanviet/vim-monokai-pro'",
    "Plugin 'tpope/vim-fugitive'",
    "Plugin 'tpope/vim-sensible'",
    "Plugin 'tpope/vim-surround'",
    "Plugin 'isobit/vim-caddyfile'",
  ]
