[brew]
  casks = [
    "1password",
    "font-fira-code-nerd-font",
    "font-fira-mono-nerd-font",
    "slack",
    "zoom",
  ]
  packages = [
    "age",
    "ansible",
    "ansible-lint",
    "atuin",
    "bat",
    "chezmoi",
    "curl",
    "diff-so-fancy",
    "direnv",
    "eza",
    "fd",
    "fzf",
    "gcc",
    "gcc@11",
    "gh",
    "git",
    "gopass",
    "go-task",
    "gomplate",
    "gum",
    "jq",
    "markdownlint-cli2",
    "ncdu",
    "nodejs",
    "npm",
    "nmap",
    "nvm",
    "pipx",
    "poetry",
    "prettyping",
    "pyenv",
    "rg",
    "rsync",
    "sd",
    "shellcheck",
    "shfmt",
    "sqlfluff",
    "sshpass",
    "starship",
    "tldr",
    "tmux",
    "unison",
    "vim",
    "yamlfmt",
    "yq",
    "z",
    "zinit",
    "zsh",
  ]
[npm]
  global_packages = ["nodemon", "express-generator", "create-react-app"]
  packages = ["express"]
[pipx]
  packages = [
    "bandit",
    "cookiecutter",
    "cruft",
    "djlint",
    "gphotos-sync",
    "jinja2-cli",
    "molecule",
    "nox",
    "playwright",
    "poetry",
    "pre-commit",
    "pylint-to-ruff",
    "pyright",
    "pytest",
    "pyupgrade",
    "ruff",
    "sshconfig",
    "streamlit",
    "tox",
    "yamllint",
  ]
