[apt]
    packages = [
        "apt-transport-https",
        "apt-utils",
        "bzip2",
        "cloc",
        "dialog",
        "dirmngr",
        "gnupg2",
        "htop",
        "inotify-tools",
        "iproute2",
        "jq",
        "less",
        "libc6",
        "libgcc1",
        "libgssapi-krb5-2",
        "libicu[0-9][0-9]",
        "libkrb5-3",
        "liblttng-ust[0-9]",
        "locales",
        "lsof",
        "lsb-release",
        "man-db",
        "manpages",
        "manpages-dev",
        "moreutils",
        "ncdu",
        "net-tools",
        "openssh-client",
        "pkg-config",
        "procps",
        "psmisc",
        "rsync",
        "socat",
        "strace",
        "sudo",
        "tree",
        "unison",
        "unzip",
        "vim",
        "xz-utils",
        "zlib1g",
        "zip",
        "zsh-autosuggestions",
    ]
[brew]
    casks = [
        "1password",
        "font-fira-code-nerd-font",
        "font-fira-mono-nerd-font",
        "slack",
        "zoom",
    ]
    packages = [
        "age",
        "atuin",
        "bat",
        "btop",
        "chezmoi",
        "coreutils",
        "curl",
        "dasel",
        "diff-so-fancy",
        "direnv",
        "eza",
        "fd",
        "findutils",
        "fzf",
        "gcc",
        "gcc@11",
        "gh",
        "git",
        "git-extras",
        "gawk",
        "gnutls",
        "gnu-indent",
        "gnu-getopt",
        "gnu-tar",
        "gnu-sed",
        "go-task",
        "gomplate",
        "grep",
        "gum",
        "jq",
        "markdownlint-cli2",
        "ncdu",
        "nmap",
        "pipx",
        "prettyping",
        "pyenv",
        "pygments",
        "rg",
        "rsync",
        "sd",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "sshpass",
        "starship",
        "tldr",
        "tmux",
        "unison",
        "vim",
        "wget",
        "yamlfmt",
        "yq",
        "z",
        "zinit",
        "zsh",
        "zsh-autosuggestions",
        "zsh-completions",
    ]
[npm]
    global_packages = [
        "nodemon",
        "express-generator",
        "create-react-app",
        "typescript",
        "ts-node",
        "nodemon",
        "tsx",
        "nx",
        "zx",
        "playwright",
        "jest",
        "eslint",
        "tsc",
        "prettier-eslint",
    ]
    packages = ["express"]
[pipx]
    packages = [
        "ansible",
        "ansible-lint",
        "bandit",
        "cookiecutter",
        "cruft",
        "djlint",
        "gphotos-sync",
        "jinja2-cli",
        "molecule",
        "nox",
        "playwright",
        "poetry",
        "pre-commit",
        "pylint-to-ruff",
        "pyright",
        "pytest",
        "pyupgrade",
        "ruff",
        "sshconfig",
        "streamlit",
        "tox",
        "yamllint",
    ]
